@startuml
hide circle

entity User{
    * id
    email
    login
    password
    first_name
    last_name
    birth_date: date
    role
}

entity Report {
    * id
    description
    state
    city
    street
    postal_code
    house_number[0..1]
    created_at: timestamp
}

entity Event {
    * id
    place
    date
    hour
    length
}

entity Commentary {
    * id
    date
    duration
    report
    user
    created_at: timestamp
}

entity ReportType {
    * name
    label
}

User |o--o{ Report : reporter
Report ||--o{ Event : organisation
Commentary }o--|| User : writer
Event ||--o{ Commentary : settlement
User }o--o{ Event : participant
User ||-up-o{ Event : creator
Report }o--|| ReportType : type

@enduml
