@startuml
hide circle

entity User{
    * id
    email
    password
    first_name
    last_name
    birth_date: date
    role
    city
    street
    zip_code
    house_number
}

entity Report {
    * id
    description
    state
    city
    street
    postal_code
    house_number[0..1]
    created_at: timestamp
}

entity Event {
    * id
    place
    date
    hour
    length
}

entity ReportType {
    * name
    label
}

User |o--o{ Report : reporter
Report ||--o{ Event : organisation
User }o--o{ Event : participant
User ||-up-o{ Event : creator
Report }o--|| ReportType : type

@enduml
